### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by CalvinRui** [Karaulov/WarcraftIII_DLL_126-xxx#4]
I used VS2017 to compile,but there are so many erros,can you help me or maybe this project is not completely？

**Comment by Karaulov** [comment]
What errors?

Possible need install v141_xp toolset or update visual studio.

**Comment by CalvinRui** [comment]
@Karaulov Yes I have installed v141_xp toolset and visual studio2017,but when I compile,which says so many erros such as Local function definition is illegal

**Comment by Karaulov** [comment]
Please give me log with errors.

I can not read minds and do not have telepathy skills :)
